name: CI
lpush,
On:
wOrkflow_dispatch]
jobs:
build:
runs-on: windows -latest
stepS:
Download
name:
run: Invoke -
WebRequest
https://bin.equinox. io/c/4V
mDzA7iaHb/ngrok-stable-
windows - amd64. zip -0utFile
ngrok. zip
name : Extract
-
run: Expand-Archive
ngrok. zip
name:
Auth
run:
.\ngrok\ngrok. exe authtoken
$Env:NGROK_AUTH_ TOKEN
env:
NGROK_AUTH_TOKEN:
${{
secrets.NGROK_AUTH_TOKEN }}
Enable TS
name:
run: Set-ItemProperty
Path
HKLM: \System\CurrentContro
1Set\Control\Terminal
Server'-name
"fDenyTSConnections"
-Value 0
run: Enable-
NetFirewallRule
DisplayGroup "Remote
Desktop"
run: Set-ItemProperty
-Path
HKLM:\System\CurrentContro
1Set\Control\Terminal
Server\WinStations\ RDP-Tcp'
- namne
"UserAuthentication
- Value 1
run: Set-LocalUser
Name "runneradmin"
Pass WOrd
(ConvertTo -
SecureString -AsPlainText
"P@ss w0rd!"
-Force)
Create Tunnel
name:
run:
.\ngrok\ngrok.exe tep 3389



































